import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/sidebar';
import SessionProvider from '@/components/providers/session-provider';

import { classNames } from '@/utils/utils';
import ConversationsDrawer from '@/components/conversations-drawer';
import SocketConnect from '@/components/socket-connect';
import { getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';
import { getUserSession } from '@/utils/actions/redis';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'WSR',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: { apple: '/chat.png' },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession();
  console.log("SESSION: ", session);

  if (!session) {
    redirect('/api/auth/signin');
  }

  const userSession = await getUserSession(session.user.email);

  return (
    <html lang="en">
      <body className={classNames(inter.className, 'relative')}>
        <SessionProvider session={session}>
          <Sidebar />
          {userSession && <SocketConnect userSession={userSession} />}
          <ConversationsDrawer />
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
